### ISSUE TITLE
Can't use local domains?

### ISSUE THREAD

**Issue by neilio** [arnemart/SafariKeywordSearchLegacy#10]
Hello!

Not sure if you're tracking issues here or not, but here goes anyway - with SafariKeywordSearch installed I can no longer access simple local domains (i.e. http://mysite/ ) - they automatically use the default search. Makes sense, but it'd be great to find a workaround for this.

I tried adding a keyword for a simple domain (mysite -> http://mysite/) but I got a weird result where nothing happens but I am no longer able to type in the address bar for that particular tab. I have to close it and create a new tab to be able to access the address bar.

**Comment by arnemart** [comment]
This is a known issue. I am considering a feature where the user can customize what triggers the default search, for now you can work around the problem by adding a period to your local domains (I put .localhost after my local domains, e.g. http://mysite.localhost/).

If you add a keyword that resolves to itself, that will create a loop that can possibly hang your browser. This is also something I'm looking into.

**Comment by arnemart** [comment]
Now that SKS uses the much more convenient `beforeSearch` event, it is up to Safari to figure out what is a URL and what is a search and I believe this issue can be closed.
