### ISSUE TITLE
Private browsing

### ISSUE THREAD

**Issue by uner** [arnemart/SafariKeywordSearchLegacy#11]
With the Holidays here I am trying to hide my shopping, and I started using Private Browsing. I noticed that if you enable Private Browsing, then quit Safari, the next time you launch, this extension, but only this extension, does not work. If you quit and relaunch again, or if you go Preferences->Extensions and turn extensions off then back on, SafariKeywordSearch works normally again.

Obviously not an important bug, and quite probably a Safari issue, but I did want to let you know.

This is with SL 10.6.8 and Safari 5.1.2.

**Comment by arnemart** [comment]
As far as I can tell, this seems to have been fixed in Safari 6.

**Comment by uner** [comment]
Confirmed, thank you!
