### ISSUE TITLE
SKS Broken on Safari 5.2 (Developer Preview/Mountain Lion)

### ISSUE THREAD

**Issue by elasticthreads** [arnemart/SafariKeywordSearchLegacy#12]
A developer preview of Safari 5.2 was released today, the most noticeable difference is an integrated Address and Search field (similiar to Chrome). This seems like a SKS killer. I hope not. While Safari does now search from the location field, its still limited to Google, Yahoo, and Bing. And there's no way to switch on the fly. But SKS doesn't work in the developer preview, and it seems like whatever API you were using won't work anymore. Any non-url gets read by Safari as a web search.

Am I (hopefully) wrong?

**Comment by arnemart** [comment]
Thanks for reporting this. I haven't had a chance to test the new safari yet, but from what you're saying it seems the API had been changed or removed. I'll investigate as soon as I can.

**Comment by arnemart** [comment]
Well this sucks. The API is still there and works, but everything that doesn't look like a URL is automatically turned into a google search and so the API is pretty much useless for this. I'll look into this and see if there are any new APIs that I can use, if not it looks like that's it for SKS. Sorry.

**Comment by kLy** [comment]
No word on this? I'm assuming this is not gonna work going forward then? :(

**Comment by arnemart** [comment]
I have reported this to Apple, but as of yet there is no reply. I have to assume nothing will be changed and that the extension won't work in 5.2.

**Comment by arnemart** [comment]
Safari Keyword Search should now work pretty well in the Safari 6 preview, minus the "default" search keyword. It does this by parsing the google search string and looking for a match.

**Comment by kLy** [comment]
Woohoo! Safari finally usable again! :D

**Comment by arnemart** [comment]
I'm happy to please :-)
