### ISSUE TITLE
Japanese text

### ISSUE THREAD

**Issue by cnet128** [arnemart/SafariKeywordSearchLegacy#13]
When the query to be searched contains Japanese text, it is inserted into the URL as "%25u" followed by the hexadecimal code for the Unicode character, instead of inserting as-is.

So for instance, a YouTube search for the query "私は" results in the URL:

http://www.youtube.com/results?search_query=%25u79C1%25u306F

instead of the expected:

http://www.youtube.com/results?search_query=私は

This issue only occurs when the Japanese text is part of the search term; other Japanese text in the URL itself works without any problems.

(Using Safari 6.0 on OS X 10.8. Love the extension, by the way. This one issue aside, it's exactly what I was looking for!)

**Comment by arnemart** [comment]
Thanks for reporting this issue. I currently use the built-in `escape`-function to URL-encode the search string, that seems to be the culprit here. I’m sure I’ll find a workaround.

**Comment by arnemart** [comment]
In fact, removing the calls to `escape` altogether fixed this issue, and doesn’t seem to have any negative consequences. Fixed in 2.0.1.
