### ISSUE TITLE
Not working in Safari 6 on Lion

### ISSUE THREAD

**Issue by skop** [arnemart/SafariKeywordSearchLegacy#15]
I can view the contextual menu item and the new configuration page, but this doesn't appear to be working in the new universal search bar in Safari 6. I'm running 10.7.4.

**Comment by arnemart** [comment]
Do you have Glims or a similar hack installed? I've heard from people with the same problem, who solved it by uninstalling Glims.

**Comment by skop** [comment]
Turning off Glims solved the problem, thanks.
