### ISSUE TITLE
Use of "&"

### ISSUE THREAD

**Issue by 9Life42** [arnemart/SafariKeywordSearchLegacy#16]
When you type a search term with the character "&" in it, everything coming after the "&" is not considered in the search. For example, searching for "me & you" results in the google search "me "

Thanks for the helpful extension!

**Comment by arnemart** [comment]
I have just discovered this bug myself. It will be fixed in the next release.

**Comment by arnemart** [comment]
Fixed in 38d05dc1a44e6d8e1796382b9a7edf4769d51493
