### ISSUE TITLE
Default search issues keyword letter

### ISSUE THREAD

**Issue by m-schmitt** [arnemart/SafariKeywordSearchLegacy#17]
With Safari Keyword Search 2.2.1 on Safari 5.1.7 (OS X 10.6.8 Snow Leopard and 10.7.4 Lion), when no keyword is entered it is expanding it to the Default _keyword_ itself, rather than that keyword's URL expansion.

For example, entering "keyword" in the URL location bar and hitting Enter results in an attempt to open "g".  

By the way, my favorite default search is a Google Browse by Name search. Browse By Name acts like "I'm Feeling Lucky" if Google is certain that the first hit is correct, but otherwise returns a normal set of search results.

**Comment by gunther82** [comment]
I have this issue too. any solution?

**Comment by arnemart** [comment]
Sorry about the late reply. Sadly, I haven't been able to reproduce this issue. Try going into keyword search settings and (re)setting your default search engine, that should hopefully take care of it.

**Comment by gunther82** [comment]
I tried that, I set Amazon as default search engine and now I got "a" if I search for a term without specifying the keyword.
Is it possible to have an older version of the extension? Because it was working fine since a few weeks ago.

**Comment by arnemart** [comment]
Could you export your settings and send them to me?

**Comment by gunther82** [comment]
{"g":"http://www.google.com/search?q=@@@","a":"http://www.amazon.com/exec/obidos/search-handle-url/index%3Dblended%26field-keywords%3D@@@","e":"http://search.ebay.com/search/search.dll?satitle=@@@","gm":"http://maps.google.it/maps?oi=map&q=@@@","imdb":"http://imdb.com/find?s=all&q=@@@","w":"http://en.wikipedia.org/wiki/Special:Search/%%%","wit":"http://it.wikipedia.org/wiki/Special:Search/%%%","wren":"http://www.wordreference.com/enit/@@@","writ":"http://www.wordreference.com/iten/@@@","y":"http://youtube.com/results?search_query=@@@"}

**Comment by arnemart** [comment]
Thanks. I have discovered a bug related to this in the code, I'll have a new release out later today to fix it.

**Comment by gunther82** [comment]
Thanks, I really appreciate this.
