### ISSUE TITLE
2.2.2, no longer works with Safari 6.0.1

### ISSUE THREAD

**Issue by freultwah** [arnemart/SafariKeywordSearchLegacy#18]
The subject line explains pretty much everything. Ever since I installed 10.8.2 and it came with Safari 6.0.1, Safari Keyword Search 2.2.2 stopped working. All keyword searches are forwarded as-is to the default search engine, whichever it happens to be.

**Comment by imanel** [comment]
Same here. It was working with 2.2.2 before update to 10.8.2 and stopped after update so it's fault of system/Safari update and not changes in 2.2.1 -> 2.2.2

**Comment by arnemart** [comment]
I am currently installing 10.8.2 myself, expect a new release of SKS later today.

**Comment by arnemart** [comment]
Turned out to be a simple oversight in my Savari version detection, the new SKS release is now out and should work perfectly in Safari 6.0.1.

**Comment by imanel** [comment]
Confirmed - working :)
Thanks mate - great job with this plugin!

**Comment by freultwah** [comment]
Same thing and the same sentiment!
