### ISSUE TITLE
Safari 12 support

### ISSUE THREAD

**Issue by NicosArv** [arnemart/SafariKeywordSearchLegacy#30]
Please consider Safari 12 support and or listing on Mac App Store. thank you

**Comment by rantanplan77** [comment]
I loved SafariKeywordSearch, but had to replace it with [Omnikey for Safari](https://github.com/marioestrada/safari-omnikey).

Both programs seem very similar, but Omnikey works with Safari 12.

**Comment by timleeuchees** [comment]
@rantanplan77 Thanks and now switch to Omnikey.

**Comment by franklouwers** [comment]
So long @arnemart, and thanks for all the fish!

**Comment by NicosArv** [comment]
> I loved SafariKeywordSearch, but had to replace it with [Omnikey for Safari](https://github.com/marioestrada/safari-omnikey).
> 
> Both programs seem very similar, but Omnikey works with Safari 12.

thanks for that, though how does one edit the keywords with omnikey? I’m in the UK so I want the keyword amazon to search amazon.co.uk vs .com? any thoughts or perhaps a a script to use for Tampermonkey? many thanks

**Comment by arnemart** [comment]
I updated the website a while ago and finally got around to updating the readme here on github. The old Safari extension API has been deprecated, and the new app extension API does not provide access to the address bar which is needed for this extension to work. Omnikey still works for now, as it is on the official extension gallery and has been signed by Apple, but it will most likely go away sometime next year.
