### ISSUE TITLE
Is it supposed to work in Safari 5.0.5 Snow Leopard?

### ISSUE THREAD

**Issue by alanruttenberg** [arnemart/SafariKeywordSearchLegacy#4]
Seems to only sort of work. 
a) Default doesn't seem to work at all
b) Settings seem to stick but not always be used. I added a new keyword and that worked, but changed the existing "g" keyword to use https://encrypted.google.com but searches using it still go to www.google.com

**Comment by arnemart** [comment]
No, it is not supposed to work in (and has not been tested with) versions of Safari below 5.1, as it relies on new extension APIs that were introduced in this version. I will clarify this in the readme.
