### ISSUE TITLE
how to add support for javascript bookmarks SafariKeywordSearch

### ISSUE THREAD

**Issue by mkarikom** [arnemart/SafariKeywordSearchLegacy#5]
first of all this extension has made safari 5.1 practical for everyday use.   I use pinboard to organize bookmarks.  i use the bookmarklet below every day to add the current page to my pinboard.in bookmarks.  it takes no arguments and works fine as a clickable link in the safari 5.1 (native) bookmarks toolbar but SKS can't open it.  how can support for this javascript be added?
thanks, matt

``` javascript
javascript:if(document.getSelection){s=document.getSelection();}else{s='';};document.location='https://pinboard.in/add?next=same&url='+encodeURIComponent(location.href)+'&description='+encodeURIComponent(s)+'&title='+encodeURIComponent(document.title)
```

**Comment by arnemart** [comment]
The latest (which I committed just now) version should support javascript bookmarklets.
