### ISSUE TITLE
Extension does not provide way to remove the Google Search box

### ISSUE THREAD

**Issue by coneybeare** [arnemart/SafariKeywordSearchLegacy#7]
One way this extension lacks vs competitors is that it offers no way to remove the google search box from the safari header. I think this is worth looking into as it is now wasted real estate

**Comment by arnemart** [comment]
Sadly, this is impossible with the current extension API.

**Comment by coneybeare** [comment]
What about providing a single bar which duplicates the behavior of the existing bar. This way we can replace the old "http bar + google bar" with your single bar?

**Comment by arnemart** [comment]
That is technically impossible, since the current address bar integrates with bookmarks and history, and the toolbar itself houses the forward/back-buttons as well as extension buttons.

**Comment by ricecakes** [comment]
Have you tried Safari Omnibar?  http://hackemist.com/SafariOmnibar/

That was the first solution I tried before stumbling across this extension.  I prefer this extension because sometimes I like having the google search bar -- call me crazy.
