### ISSUE TITLE
Spaces sometimes need percent-encoding

### ISSUE THREAD

**Issue by vasi** [arnemart/SafariKeywordSearchLegacy#8]
Attempting to search Wikipedia for the Delta II rocket with "w Delta II" yields the URL http://en.wikipedia.org/wiki/Special:Search/delta+ii , which doesn't go to the right place. For Wikipedia at least, spaces in the search string should be percent-encoded, i.e.: http://en.wikipedia.org/wiki/Special:Search/delta%20ii .

Perhaps @@@ in query specs should continue to mean "use + for spaces", while %%% could be added for "percent-encode spaces"?

**Comment by arnemart** [comment]
Brilliant idea, and a much simpler solution to the problem than the one I was considering implementing. Hereby fixed.
