### ISSUE TITLE
Spaces encoded inconsistently

### ISSUE THREAD

**Issue by ricecakes** [arnemart/SafariKeywordSearchLegacy#9]
Spaces seem to be encoded inconsistently.  I typed in several words for a shortcut that uses @@@ for the replacement and the first space gets encoded as + while all subsequent spaces turn into %20.

(As an aside, thanks so much for creating this extension and your quick work earlier about answering these issues about encoding spaces!)

**Comment by arnemart** [comment]
I know -- I have already fixed it, just forgotten to release it. Will hopefully get around to it shortly.
